### PR TITLE
Speed Improvement by Using Numpy

### PR DESCRIPTION
**Pull request by frigorific44**
I am working with approximately one-thousand parties and thousands of seats to assign for each computation, and the slow (for my purposes) speed of many of the algorithms served as the motivation for the changes I am proposing.

With a rough test, my proposed changes brought the time of consecutively computing the apportionment of each algorithm on 1000 parties and 5000 seats from 7 minutes, to under 5 seconds. This is also not including Quota, which was slow enough before that it hadn't finished after tens of minutes, but also now only takes a few seconds.

This was done by converting what operations I could to use Numpy arrays and functions. This helps to eliminate a few (comparatively) costly loops, as well as to improve data lookup speeds since Numpy arrays are able to be stored as contiguous blocks. In order to preserve the signature of the methods, lists are converted to Numpy arrays internally and then converted back to lists before being returned. There may be better places in the code to do this, but I used my best judgement.

There was a couple of places where `Fraction`s  were used that I wasn't sure about. My interpretation is that this was to prevent rounding errors, but given the operations that followed it didn't seem like it actually would have prevented this. Again, that was my best interpretation as I wasn't sure, so perhaps there was a different motivation for their use. I believe I have seen Numpy suggested before to remedy rounding errors anyways, as well as I'm not sure it would be much of an issue, but if the specific use of `Fraction` is quite essential, I can perhaps try to work towards a more satisfying compromise. After some searching I had found that it is possible to use an array of `Fraction`s, but it would have to be an `object` array, and this would negate any of the benefits normally found from using Numpy arrays; otherwise, I would have done my best to keep them.

As you may imagine, certain operations gained more marginal improvements than others, but I hope that the overall improvement demonstrated is encouraging enough to accept these changes. Please let me know if there's anything further I can do, or if there are any changes you would like to see before accepting the pull request.

Also, I ought to mention that this commit did indeed pass the unit tests, which had helped to shed light on a few errors I had made.

### CODE REVIEW

**Comment by martinlackner** [comment]
What a great contribution! I am very happy about these improvements and would like to include them.

However, I would prefer if we could keep the original code based on fractions alongside your faster numpy code. The reason is that at some points in the code we compare numbers (concrete example see below) - and using numpy that would mean comparing floats. This is not really a issue, because in the worst case it only matters in the case of ties (unlikely) and even then can only influence the order in which ties are broken. Still, for comparison and to have a certainly correct solution, I'd like to keep the fractions code.

Would you be willing to change your PR in the following way?
Each method has a parameter `fractions`. By default it is `False`, i.e., your numpy code is used. If it is set to `True`, the original code is used. Looking at your PR, I think this should be possible with minimal code duplication.
Advantage: I can strengthen the unit tests to run both versions.

Let me know what you think.

----

Example for comparing numbers:

https://github.com/martinlackner/apportionment/blob/0b5ea8669b470dbb3bcbe86923d9d2fd5652d8a8/apportionment/methods.py#L245

If `weights[i]` contains a number slightly smaller than `minweight` (due to rounding), it will not be considered here. This basically means that the tie is broken in disfavor of party `i` but no corresponding message is printed. I am not sure if this actually can happen (with reasonably sized numbers), but to be sure I'd like to keep the old code as well.

**Comment by martinlackner** [comment]
Many thanks for your work, @frigorific44 !

**Comment by frigorific44** [comment]
Of course @martinlackner , it was my pleasure! I was a little quiet because after looking back at my pull request, I was embarrassed to think it could have come across as somewhat rude. Maybe this was not the case, but I'm sorry if it was! Either was, I'm glad I was able to contribute.

After you explained it, the importance of using the fractions was much more clear to me, so thank you. In bringing them back and adding the flag, I did run into overflow errors when using the fractions. It turned out that the fractions were still using Numpy fixed-size data-types rather than native Python integers, so I did have to fix that.

It isn't too important, but if it seemed like there was extra casting to integers, that's why.

**Comment by martinlackner** [comment]
No worries @frigorific44 , that was not my perception! I am really happy about your contribution.

I am not quite sure whether I understand the problem you are describing. Could you send me an example? (Of course, if you already have a fix, feel free to open a PR!)

**Pull request merged**
